### ISSUE TITLE
add well-supported storage backend for vault

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/prod#44]
please put your configuration in code with terraform

**Comment by pivotal-bin-ju** [comment]
TODOs:
- [ ] scalable storage backend
  - [ ] research the available backend
  - [ ] secrets copy
  - [ ] switch the backend for `nci`
- [ ] auto-unseal 
   - [ ] auto-unseal with Google Cloud Key Management Service ([extraEnvVars in values.yaml](https://github.com/hashicorp/vault-helm/blob/faf5a84c5e9e9dd18d4ba6b914b37e356c6022ab/values.yaml#L62-L67), 
   - [ ] [auto-unseal settings in vault config file](https://github.com/hashicorp/vault-helm/blob/faf5a84c5e9e9dd18d4ba6b914b37e356c6022ab/values.yaml#L196-L204), 
   - [ ] [sample terraform config for gcpkms](https://github.com/hashicorp/vault-helm/blob/0342358c945b247ba772c89ca97517123fafca99/test/terraform/main.tf#L25-L37),
   - [ ] [terraform docs for gcpkms](https://www.terraform.io/docs/providers/google/r/kms_key_ring.html))
- backup plan

**Comment by pivotal-jamie-klassen** [comment]
@deniseyu made some nice notes on this topic in #37, so I'd say they should both close at the same time

**Comment by pivotal-bin-ju** [comment]
### Research on the _storage_ and _backup_ for `vault`
1.` Postgresql/Cloudsql` or `gcs`?  
Please see the discussion  on [slack](https://pivotal.slack.com/archives/GBHN4GXTR/p1575059591441800)

`gcs` with its simple configuration and  SLA around data integrity seems like the best choice.
When we look into the `backup/restore` for `vault`, it does not guarantee an atomic operation when talking to the storage backend, even low-level interface is exposed to `postgresql` backend. so it is not safe to snapshot the backend when it is running. Stop it while doing a backup which makes no sense.
Luckily for our case, the most frequent interaction with `vault` is reading, not writing. so theoretically we have very low chance to get inconsistent data while we do a backup.

Base on the assumption above, we should be OK to backup the online `vault`.  `gcs` object `versioning` may be hard to track and the performance would be low when data is frequently updated.  
Leveraging the automatic backup of `cloudsql` may benefit us.

- configuration for  `postgresql/cloudsql`:
```
storage "postgresql" {
  connection_url = "postgres://user123:secret123!@localhost:5432/vault"
}
```
(Do we need another `vault` to keep the password for the connection? :) )

- Manual steps for initialization:
  - create table `vault_kv_store`
     ```
     CREATE TABLE vault_kv_store (
       parent_path TEXT COLLATE "C" NOT NULL,
       path        TEXT COLLATE "C",
       key         TEXT COLLATE "C",
       value       BYTEA,
       CONSTRAINT pkey PRIMARY KEY (path, key)
     );
     
     CREATE INDEX parent_path_idx ON vault_kv_store (parent_path);
     ```
  - To support HA feature:
     ```
     CREATE TABLE vault_ha_locks (
       ha_key                                      TEXT COLLATE "C" NOT NULL,
       ha_identity                                 TEXT COLLATE "C" NOT NULL,          
       ha_value                                    TEXT COLLATE "C",  
       valid_until                                 TIMESTAMP WITH TIME ZONE NOT NULL,
       CONSTRAINT ha_key PRIMARY KEY (ha_key)
     );
     ```
  - do not need to create the function `vault_kv_put`due to the newer version will be used than 9.5.
  - more detail please see [the storage configuration](https://www.vaultproject.io/docs/configuration/storage/postgresql.html)

**Comment by pivotal-bin-ju** [comment]
**DEV NOTE**
What I did:
- terraform: added a new `cloudsql/postgres` as the backend of `vault`
- chart: deployed a new chart `vault-nci`
remained Issues:
 the chart now complain the issue: 
```
Error initializing storage of type postgresql: failed to check for native upsert: pq: Private key file has group or world access. Permissions should be u=rw (0600) or less
```
**To Do**:
- Solve the problem above
- Check the to-do list

**Comment by deniseyu** [comment]
Can the auto-unseal and backend changes exist as separate PRs?

**Comment by zoetian** [comment]
@deniseyu yeah that makes sense. Originally it seemed easier to do both "while you're at it", but both tasks are pretty big and worth splitting apart

**Comment by pivotal-bin-ju** [comment]
**Dev Note**
Today I:
- populated the secret on `lastpass`, so you can load the secret by running `make creds-vault-nci`
- read `postgres` IP and secret from k8s secrets.

**Next**
check out the [TODO list](https://github.com/concourse/prod/issues/44#issuecomment-559865811)

**Comment by pivotal-bin-ju** [comment]
The data has been ported from `ci` to `nci` which has postgres as backend, and the auto backup is enabled.
